name: website

custom:
  # user: ${env:USER}

website:
  component: '@serverless/website'
  inputs:
    src:
      src: ./src
      hook: yarn run build
      dist: ./dist
    domain: tingdong.dev.bellhop.io
  plugins:
    - serverless-offline
