name: website

website:
  component: '@serverless/website'
  inputs:
    src:
      src: ./src
      hook: yarn run build
      dist: ./dist
    domain: ${env:USER}.dev.bellhop.io
  plugins:
    - serverless-offline
