version: "3"
services:
  web:
    container_name: samantha-web
    image: samantha-web:${IMAGE_TAG:-local}
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - server
      - hasura
    volumes:
      - ./web:/app
    ports:
      - 2000:2000
    command: yarn -s start:dev

  postgres:
    image: postgres:latest
    container_name: samantha-postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  hasura:
    container_name: samantha-hasura
    image: hasura/graphql-engine:v1.3.3
    restart: always
    depends_on:
      - postgres
    env_file:
      - database.env
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/hasura
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - ACTION_BASE_URL=http://server:3020
      - M1_BLOCK_STATE_UPDATE_WEBHOOK_URL=http://server:3020/block_state_update
      - M2_BLOCK_STATE_UPDATE_WEBHOOK_URL=http://server:3020/m2_block_state_update
    ports:
      - "8080:8080"
    command: graphql-engine serve

  server:
    container_name: samantha-server
    image: samantha-server:${IMAGE_TAG:-local}
    build:
      context: ./hasura
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - hasura
    environment:
      - NODE_ENV=development
      - HASURA_GRAPHQL_ENDPOINT=http://hasura:8080
      - HASURA_GRAPHQL_CLI_ENVIRONMENT=default
      - HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION=false
    volumes:
      - ./hasura/src:/app/src
    ports:
      - "3000:3000"
    # command: sh -c "yarn hasura:migrate && yarn hasura:metadata && yarn dev"
    command: yarn dev

  admin:
    container_name: samantha-admin
    image: samantha-admin:${IMAGE_TAG:-local}
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - hasura
    ports:
      - "3030:3030"
    stdin_open: true
    volumes:
      - ./admin:/app
    command: yarn start

volumes:
  postgres_data:
