version: "3"
services:
  web:
    image: samantha-web:${WEB_IMAGE_TAG:-latest}
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: samantha-web
    restart: always
    depends_on:
      - postgres
      - server
      - hasura
    ports:
      - 2000:2000
    command: yarn -s start:prod

  postgres:
    image: postgres:latest
    container_name: samantha-postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.2.2
    container_name: samantha_hasura
    restart: always
    depends_on:
      - postgres
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:g+CzXRVFufp7YfFgJbgmpVCb@postgres:5432/hasura
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=qcA.wmEfFzDpfzZZoepJs7gw
    ports:
      - "8080:8080"
    command: graphql-engine serve

  server:
    image: samantha-server:${SERVER_IMAGE_TAG:-latest}
    build:
      context: ./hasura
      dockerfile: Dockerfile
    container_name: samantha-server
    restart: always
    depends_on:
      - postgres
      - hasura
    environment:
      - NODE_ENV=production
      - HASURA_GRAPHQL_ENDPOINT=http://hasura:8080
      - HASURA_GRAPHQL_CLI_ENVIRONMENT=default
      - HASURA_GRAPHQL_SHOW_UPDATE_NOTIFICATION=false
    ports:
      - "3000:3000"
    command: sh -c "yarn hasura:migrate && yarn hasura:metadata && yarn start"

volumes:
  postgres_data:
