version: "3"
services:
  postgres:
    image: postgres
    container_name: my_postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=g+CzXRVFufp7YfFgJbgmpVCb
      - POSTGRES_DB=hasura
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:v1.2.2
    container_name: my_hasura
    depends_on:
      - postgres
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:g+CzXRVFufp7YfFgJbgmpVCb@postgres:5432/hasura
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=qcA.wmEfFzDpfzZZoepJs7gw
    ports:
      - "8080:8080"
  server:
    image: samantha-server:latest
    container_name: my_server
    depends_on:
      - postgres
      - hasura
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: yarn dev

volumes:
  my_dbdata:
