version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hasura
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:v1.2.2
    depends_on:
      - postgres
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/hasura
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET='myadminsecretkey'
    ports:
      - "8080:8080"

volumes:
  my_dbdata: