on:
  push:
    tags:
      - "*"

name: Production Deployment to Amazon ECS

jobs:
  deploy:
    name: Production Deployment
    runs-on: [self-hosted, Linux, X64]
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_DEPLOY_ENVIRONMENT: ${{ secrets.SENTRY_DEPLOY_ENVIRONMENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Create new Sentry release
      #   id: sentry
      #   run: |
      #     # Install Sentry CLI
      #     curl -sL https://sentry.io/get-cli/ | bash

      #     # Create new Sentry release
      #     export SENTRY_RELEASE=$(sentry-cli releases propose-version)
      #     echo "::set-env name=SENTRY_RELEASE::$SENTRY_RELEASE"

      #     echo "sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE"
      #     sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
      #     sentry-cli releases set-commits --auto $SENTRY_RELEASE
      #     sentry-cli releases finalize $SENTRY_RELEASE

      #     # Create new deploy for this Sentry release
      #     sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push server image to Amazon ECR
        id: build-server-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_SERVER_REPOSITORY: samantha-server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/hasura
          docker build -t $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=server_image::$ECR_REGISTRY/$ECR_SERVER_REPOSITORY:$IMAGE_TAG"

      - name: Build, tag, and push web image to Amazon ECR
        id: build-web-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_WEB_REPOSITORY: samantha-web
          IMAGE_TAG: ${{ github.sha }}
          SENTRY_RELEAES: ${{ steps.sentry.outputs.SENTRY_RELEASE }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/web
          docker build -t $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$IMAGE_TAG --build-arg sentry_release=${SENTRY_RELEASE} .
          docker push $ECR_REGISTRY/$ECR_WEB_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=web_image::$ECR_REGISTRY/$ECR_WEB_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new samantha-server image ID in the Amazon ECS task definition
        id: task-def-server
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/prod.json
          container-name: server
          image: ${{ steps.build-server-image.outputs.server_image }}

      - name: Fill in the new samantha-web image ID in the Amazon ECS task definition
        id: task-def-web
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-server.outputs.task-definition }}
          container-name: web
          image: ${{ steps.build-web-image.outputs.web_image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-web.outputs.task-definition }}
          service: samantha_service
          cluster: samantha
          wait-for-service-stability: true
